-- Sensei store registry seed — ~49 Dutchie slugs from the existing scripts,
-- deduped (`stoop` appeared in both old lists). Store list is DATA, not code:
-- expanding coverage means adding rows here (or via the dashboard), not editing
-- the pipeline. Idempotent: safe to re-run.

insert into public.stores (slug, provider, active) values
  ('buzzy-ny','dutchie',true),
  ('gram-cannabis-dispensary','dutchie',true),
  ('flowery','dutchie',true),
  ('high-of-brooklyn','dutchie',true),
  ('dagmar-cannabis-williamsburg','dutchie',true),
  ('citiva-medical-llc-brooklyn','dutchie',true),
  ('verdi-park-slope','dutchie',true),
  ('cbj-retail','dutchie',true),
  ('hybrid-nyc','dutchie',true),
  ('conbud-les','dutchie',true),
  ('dazed-cannabis1','dutchie',true),
  ('stoop','dutchie',true),
  ('culture-house','dutchie',true),
  ('ny-canna-co-5th-ave','dutchie',true),
  ('qube-manhattan','dutchie',true),
  ('torches-nyc','dutchie',true),
  ('the-emerald-dispensary-manhattan','dutchie',true),
  ('temeka-bleecker','dutchie',true),
  ('gotham-nyc-3rd-st','dutchie',true),
  ('organic-relief-leaf','dutchie',true),
  ('the-flowery-east-village','dutchie',true),
  ('the-doe-store','dutchie',true),
  ('sky-high-club','dutchie',true),
  ('green-genius-nyc','dutchie',true),
  ('verdi','dutchie',true),
  ('gotham-chelsea','dutchie',true),
  ('smiley-exotics','dutchie',true),
  ('baiked','dutchie',true),
  ('blazinup','dutchie',true),
  ('afny','dutchie',true),
  ('twenty-one-thirty','dutchie',true),
  ('gotham-buds','dutchie',true),
  ('elevate-soho','dutchie',true),
  ('smelly-nelly-queens','dutchie',true),
  ('bloomlee-iii','dutchie',true),
  ('robin-hood-cannabis-west-broadway','dutchie',true),
  ('the-daily-green','dutchie',true),
  ('healthy-choice','dutchie',true),
  ('terp-bros-astoria','dutchie',true),
  ('rnr-dispensary','dutchie',true),
  ('tango-hotel-charlie-ventures','dutchie',true),
  ('weedkraft','dutchie',true),
  ('pryzm','dutchie',true),
  ('gmdss-llc','dutchie',true),
  ('hii','dutchie',true),
  ('green-jungle','dutchie',true),
  ('dominica62','dutchie',true),
  ('sweet-life-nyc','dutchie',true)
on conflict (slug) do nothing;
